server:
  port: 8088

mcp:
  public-base-url: http://127.0.0.1:8088
  sse:
    enabled: false

spring:
  application:
    name: mcp-server-demo
  main:
    banner-mode: off

crm:
  api:
    base-url: http://192.168.1.250:9999/uac
    auth-header-name: authorization
    auth-prefix: "Bearer "

logging:
  level:
    root: DEBUG
    org.springframework.ai: DEBUG
    com.example.mcp: DEBUG
