server:
  port: 8088

mcp:
  public-base-url: http://8.147.68.53:8088

spring:
  application:
    name: mcp-server-demo
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: mcp-server-demo
        version: 1.0.0
        type: SYNC
        stdio: false
        base-url: ${mcp.public-base-url}
        sse-endpoint: /mcp
        sse-message-endpoint: /mcp

crm:
  api:
    base-url: http://192.168.1.250:9999/uac
    auth-header-name: authorization
    auth-prefix: "Bearer "

logging:
  level:
    root: ERROR
    org.springframework.ai: ERROR
    com.example.mcp: ERROR
